-- Aegis Claims Platform — schema.
-- Applied automatically by the postgres container on first boot (see docker-compose.yml).
-- Hand-maintained DDL; there is no ORM/migration framework in this legacy estate.

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT PRIMARY KEY,
    username      VARCHAR(64) UNIQUE NOT NULL,
    -- Passwords are stored as salted BCrypt hashes (see auth.PasswordHasher).
    -- BCrypt digests are 60 chars; column is sized to fit legacy MD5 hex too.
    password_hash VARCHAR(72) NOT NULL,
    full_name     VARCHAR(128) NOT NULL,
    email         VARCHAR(128),
    role          VARCHAR(16) NOT NULL DEFAULT 'MEMBER', -- MEMBER | ADJUSTER | ADMIN
    created_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS policies (
    id             BIGINT PRIMARY KEY,
    policy_number  VARCHAR(32) UNIQUE NOT NULL,
    holder_user_id BIGINT NOT NULL REFERENCES users(id),
    product        VARCHAR(64) NOT NULL,
    status         VARCHAR(16) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE | LAPSED | CANCELLED
    premium_cents  BIGINT NOT NULL DEFAULT 0,
    effective_date DATE NOT NULL,
    end_date       DATE
);

CREATE TABLE IF NOT EXISTS claims (
    id               BIGINT PRIMARY KEY,
    claim_number     VARCHAR(32) UNIQUE NOT NULL,
    policy_id        BIGINT NOT NULL REFERENCES policies(id),
    -- The member the claim belongs to. Authorization on the claim-detail endpoint
    -- is SUPPOSED to be enforced against this column but is not (CWE-639).
    member_user_id   BIGINT NOT NULL REFERENCES users(id),
    claim_type       VARCHAR(32) NOT NULL,
    status           VARCHAR(16) NOT NULL DEFAULT 'SUBMITTED',
                     -- SUBMITTED | VALIDATED | ADJUDICATED | PAID | DENIED
    amount_cents     BIGINT NOT NULL DEFAULT 0,
    approved_cents   BIGINT,
    diagnosis_code   VARCHAR(16),
    adjudicator_notes TEXT,
    submitted_at     TIMESTAMP NOT NULL DEFAULT now(),
    adjudicated_at   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS claim_lines (
    id           BIGINT PRIMARY KEY,
    claim_id     BIGINT NOT NULL REFERENCES claims(id),
    service_code VARCHAR(16) NOT NULL,
    description  VARCHAR(256),
    billed_cents BIGINT NOT NULL DEFAULT 0,
    allowed_cents BIGINT
);

CREATE TABLE IF NOT EXISTS invoices (
    id             BIGINT PRIMARY KEY,
    invoice_number VARCHAR(32) UNIQUE NOT NULL,
    policy_id      BIGINT NOT NULL REFERENCES policies(id),
    member_user_id BIGINT NOT NULL REFERENCES users(id),
    amount_cents   BIGINT NOT NULL DEFAULT 0,
    status         VARCHAR(16) NOT NULL DEFAULT 'OPEN', -- OPEN | PAID | OVERDUE | VOID
    due_date       DATE,
    created_at     TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payments (
    id           BIGINT PRIMARY KEY,
    invoice_id   BIGINT NOT NULL REFERENCES invoices(id),
    amount_cents BIGINT NOT NULL DEFAULT 0,
    method       VARCHAR(16) NOT NULL DEFAULT 'ACH', -- ACH | CARD | CHECK
    status       VARCHAR(16) NOT NULL DEFAULT 'PENDING', -- PENDING | SETTLED | FAILED
    external_ref VARCHAR(64),
    created_at   TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS documents (
    id            BIGINT PRIMARY KEY,
    claim_id      BIGINT REFERENCES claims(id),
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    filename      VARCHAR(256) NOT NULL,
    stored_path   VARCHAR(512) NOT NULL,
    content_type  VARCHAR(128),
    uploaded_at   TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action        VARCHAR(64) NOT NULL,
    entity        VARCHAR(32),
    entity_id     VARCHAR(32),
    detail        TEXT,
    created_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reconciliation_runs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date        DATE NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'RUNNING', -- RUNNING | OK | DISCREPANCY | FAILED
    matched_count   INT NOT NULL DEFAULT 0,
    unmatched_count INT NOT NULL DEFAULT 0,
    notes           TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

-- Indexes are sparse on purpose; the claims-list / billing hot paths do N+1 lookups
-- rather than joins (see REVIEW.md, "seeded inefficiencies").
CREATE INDEX IF NOT EXISTS idx_claims_member ON claims(member_user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_member ON invoices(member_user_id);
